name: test_mongo
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  mongo_dart: ^0.7.4+1
  equatable: ^2.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0
  json_annotation: any

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  build_runner: ^2.1.0
  injectable_generator: ^1.5.3
  json_serializable: any
